language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.6"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  # install Turnstile, use `master` branch
  - git clone https://github.com/stchang/macrotypes.git
  - raco pkg install --auto macrotypes/macrotypes-lib/
  - raco pkg install --auto macrotypes/turnstile-lib/
  - raco pkg install --auto macrotypes/rackunit-macrotypes-lib/

install:
 - raco pkg install --auto cur-lib/
 - raco pkg install --auto cur-test/

script:
 - raco test --package cur-test
 - raco setup